version: "3.8"
services:
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server-db,1433;Database=fauno;User Id=sa;Password=SuaSenha!;TrustServerCertificate=True;
    depends_on:
      - sql-server-db

  frontend:
    build:
      context: ./UI
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - api

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SuaSenha!"